# 1.Print 'Hello HCIA'.

In [1]:
print('Hello HCIA')

Hello HCIA


# 2.Define two variables and calculate their sum.

In [10]:
a = 2
b = 9
a + b

11

# 3.Define a list and replicate in three different ways.

In [15]:
import copy

l = [1,2]
replica_one = l[:]
replica_two = l.copy()
replica_three = copy.deepcopy(l)
print(replica_one, replica_two, replica_three)

[1, 2] [1, 2] [1, 2]
[1, 2] [1, 2] [1, 2]


# 4.Define two lists and merge them together.

In [18]:
a = [0,1]
b = [2,3,4]
a.extend(b)

# 5. Get the last element of the list and print it.

In [21]:
a[-1]

4

# 6.Define a tuple that contains only one element.

In [28]:
tup = (1,)
print(type(tup), 'len', len(tup))

<class 'tuple'> len 1


# 7.Define a three-line long string.

In [41]:
long_string = """Hi!
It's a three-line long string
By the way, what does long mean?"""
print (long_string)

Hi!
It's a three-line long string
By the way, what does long mean?


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [42]:
tup = (0,1,2,3,4,5)
for i in tup: print(i)

0
1
2
3
4
5


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [43]:
def mul(a,b):
    return a * b
print(mul(8,6))

48


# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [45]:
import numpy as np
arr_5_x_5 = np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [46]:
arr_4_x_6 = np.zeros((4,6))

# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [67]:
arr = np.arange(15,)
arr.resize(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [69]:
matrix_1 = np.array([[1,2],[3,4],[5,6]])
matrix_2 = np.array([[10,10,10],[1,1,1]])
print( matrix_1.dot(matrix_2))

[[12 12 12]
 [34 34 34]
 [56 56 56]]
